version: '3'
services:
  web:
    #build: .
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    restart: always

  php:
    build: .
    #image: php:7-fpm
    volumes:
          - ./:/var/www/html
    restart: always
    ports:
        - 9000:9000